version: '2'

services:
  django:
    volumes:
      - .:/code
  spark:
    extends:
      service: django
    image: docker.io/bitnami/spark:3-debian-10
    environment:
      - SPARK_MODE=master
  spark-worker:
    extends:
      service: spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=521M
      - SPARK_WORKER_CORES=1