services:
  django:
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py initadmin && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
  spark:
    ports:
      - '8080:8080'
  spark-worker:
    ports:
      - '8081:8081'
